#!/usr/bin/env bash

pwd="$(dirname "$BASH_SOURCE")"
docker_tag="$(cat $pwd/build-docker | grep "docker_tag=" | cut -d "=" -f 2)"

export $(grep -v '^#' .env | xargs)
if [ ! -d "$tmp_dir" ]; then
    mkdir -p "$tmp_dir"
fi

daemon_flag=""
if [ "$1" = '-d' ]; then
    daemon_flag='-d'
fi

docker run $daemon_flag \
    -p $server_port:$server_port \
    --mount "type=bind,src=$tmp_dir,dst=/tmp" \
    --mount "type=bind,src=$server_public_root,dst=$server_public_root" \
    --env-file .env \
    -t $docker_tag
