#!/usr/bin/env bash

export $(grep -v '^#' .env | xargs)

if [ -z $server_virtual_host ]; then
    echo -e "Variable server_virtual_host is not set.\nPlease configure it on the .env file."
fi

files=$(find "$server_public_root" -type f -name "*.html")
for file in $files; do
    sed -i "s#<base href=".*">#<base href='"$server_public_root"'>#g" "$file"
done
